import { createSlice } from '@reduxjs/toolkit'
import { MediaState } from 'src/types/types'

const initialState: MediaState = {
  media: [
    {
      format: 'jpeg',
      link: '/img/mediaLib/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/4.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/5.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/6.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/7.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/8.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/9.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/10.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/11.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/12.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/4.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/5.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/6.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/7.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/8.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/9.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/10.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/11.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/12.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/4.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/5.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/6.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/7.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/8.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/9.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/10.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/11.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/12.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/4.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/5.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/6.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/7.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/8.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/9.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/10.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/11.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/12.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'jpeg',
      link: '/img/mediaLib/4.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'image',
    },
    {
      format: 'avi',
      link: '/img/mediaLib/videoPreview/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'video',
    },
    {
      format: 'mp4',
      link: '/img/mediaLib/videoPreview/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'video',
    },
    {
      format: 'mp4',
      link: '/img/mediaLib/videoPreview/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'video',
    },
    {
      format: 'avi',
      link: '/img/mediaLib/videoPreview/1.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'video',
    },
    {
      format: 'mp4',
      link: '/img/mediaLib/videoPreview/2.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'video',
    },
    {
      format: 'mp4',
      link: '/img/mediaLib/videoPreview/3.jpg',
      publishDate: new Date().toISOString(),
      title: 'Title test',
      type: 'video',
    },
  ],
}

export const mediaSlice = createSlice({
  name: 'media',
  initialState,
  reducers: {},
})

// eslint-disable-next-line no-empty-pattern
export const {} = mediaSlice.actions

export default mediaSlice.reducer
